"""add project_id to activity log, make task_id nullable and run it

Revision ID: 60dfd813f363
Revises: defdbbda1ad4
Create Date: 2026-06-23 07:56:21.625746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60dfd813f363'
down_revision: Union[str, Sequence[str], None] = 'defdbbda1ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
