"""Added listing

Revision ID: a2aa71bb3717
Revises: 45d8bf5d21c4
Create Date: 2026-06-22 07:47:49.087961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2aa71bb3717'
down_revision: Union[str, Sequence[str], None] = '45d8bf5d21c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'done')
    # ### end Alembic commands ###
