"""add project_id to activity log, make task_id nullable

Revision ID: defdbbda1ad4
Revises: 8a74b52e25b9
Create Date: 2026-06-23 07:52:35.598926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'defdbbda1ad4'
down_revision: Union[str, Sequence[str], None] = '8a74b52e25b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activity_logs', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_column('activity_logs', 'project_id')
    # ### end Alembic commands ###
