# Generated by Django 6.0.6 on 2026-06-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Authorization',
        ),
    ]
