# Generated by Django 6.0.6 on 2026-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_rename_todo_authorization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorization',
            old_name='title',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='authorization',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='authorization',
            name='lastname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
