# Generated by Django 6.0.6 on 2026-06-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_rename_title_authorization_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
